{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.service.port }}
          envFrom:
            {{- if .Values.ui.additionalEnvFrom }}
              {{- range .Values.ui.additionalEnvFrom }}
                - configMapRef:
                    name: {{ .configMapRef.name }}  # Reference the ConfigMap name
              {{- end }}
            {{- else }}
              # Optionally, if no envFrom values are provided, provide defaults
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.port }}
  selector:
    app: ui
{{- end }}
